### ISSUE TITLE
I'm having a error with nf-core/mag

### ISSUE THREAD

**Issue by ramakrishnas** [nf-core/mag#119]
Hi, 
I'm trying to run the nf-core/mag pipeline on hpc cluster. when I ran the profile test 

nextflow run nf-core/mag -profile test

it gave the following error. I greatly appreciate for all your help.

[68/ce5ef3] NOTE: Process `phix_download_db (GCA_002596845.1_ASM259684v1_genomic.fna.gz)` terminated with an error exit status (139) -- Execution is retried (1)
Error executing process > 'get_busco_version'

Caused by:
  Process `get_busco_version` terminated with an error exit status (127)

Command executed:

  busco --version > v_busco.txt

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: busco: command not found

**Comment by apeltzer** [comment]
Transferred this to the appropriate repository `mag`.

**Comment by ramakrishnas** [comment]
we use SGE scheduler on our cluster

Yes, you are right, I did not use singularity.

Here is the command that I ran
nextflow run nf-core/mag -profile test

when I ran with singularity container
 nextflow run nf-core/mag -profile test,singularity

I got the following error
Error executing process > 'kraken2_db_preparation (1)'

Caused by:
  Failed to pull singularity image
  command: singularity pull  --name nfcore-mag-1.1.0.img docker://nfcore/mag:1.1.0 > /dev/null
  status : 143
  message:
    INFO:    Converting OCI blobs to SIF format
    INFO:    Starting build...
    Getting image source signatures
    Copying blob sha256:68ced04f60ab5c7a5f1d0b0b4e7572c5a4c8cce44866513d30d9df1a15277d6b
    Copying blob sha256:9c388eb6d33c40662539172f0d9a357287bd1cd171692ca5c08db2886bc527c3
    Copying blob sha256:96cf53b3a9dd496f4c91ab86eeadca2c8a31210c2e5c2a82badbb0dcf8c8f76b
    Copying blob sha256:6b5e6e9d001075f1740c33c76ef98f510fb808dd7d6f8edf6aa7d7db6248d9a1
    Copying blob sha256:e013801287a05245b86a6f03422be5ba4791b7db37de109c84767633fefa840d
    Copying blob sha256:933e1ed248f5470a3939dfd6467d28365355726f793951fdf819528d180aff00
    Copying blob sha256:e627393bf2016c751efed5e0d1dc2d1b9d4086396dda7422bfe0a32d31b56b5f
    Copying blob sha256:6d40bd2b2084d2d569c9b30ef0966f16bfacad3764d56903e623dea946e373a3
    Copying blob sha256:6b06b45ef97476781692af9ae1985dcd1267860cc0f56dbdbffa2912f2b0ef3b
    Copying config sha256:894b836d2c8e1f46975257c1946e4ba57dc7317a9b081525e0df0506dde9f00c
    Writing manifest to image destination
    Storing signatures
    2020/10/21 10:22:57  info unpack layer: sha256:68ced04f60ab5c7a5f1d0b0b4e7572c5a4c8cce44866513d30d9df1a15277d6b
    2020/10/21 10:23:05  info unpack layer: sha256:9c388eb6d33c40662539172f0d9a357287bd1cd171692ca5c08db2886bc527c3
    2020/10/21 10:23:24  info unpack layer: sha256:96cf53b3a9dd496f4c91ab86eeadca2c8a31210c2e5c2a82badbb0dcf8c8f76b
    2020/10/21 10:23:39  info unpack layer: sha256:6b5e6e9d001075f1740c33c76ef98f510fb808dd7d6f8edf6aa7d7db6248d9a1
    2020/10/21 10:23:39  info unpack layer: sha256:e013801287a05245b86a6f03422be5ba4791b7db37de109c84767633fefa840d
    2020/10/21 10:23:39  info unpack layer: sha256:933e1ed248f5470a3939dfd6467d28365355726f793951fdf819528d180aff00

I'm not sure what to change in the config file

Thank you much again for your help

**Comment by d4straub** [comment]
The most recent issue could be a singularity issue. It might be that your singularity versions is outdated. It might be also possible that this process takes too long and therefore is terminated.
Both of these problems might be solved by you downloading the singularity image and then using that image for the pipeline:
```
singularity pull --name nfcore-mag-1.1.0.img docker://nfcore/mag:1.1.0
nextflow run nf-core/mag -r 1.1.0 -profile test -with-singularity nfcore-mag-1.1.0.img
```
Please let me know if this solves the issue or not.

**Comment by ramakrishnas** [comment]
Daniel, thanks for the message.

Now, I'm getting a different error

-[nf-core/mag] Pipeline completed with errors-
Error executing process > 'remove_phix (test_minigut_sample2)'

Caused by:
  Process requirement exceed available CPUs -- req: 2; avail: 1

Command executed:

  bowtie2 -p "2"                     -x ref                     -1 "test_minigut_sample2_trimmed_R1.fastq.gz"                     -2 "test_minigut_sample2_trimmed_R2.fastq.gz"                     --un-conc-gz test_minigut_sample2_phix_unmapped_%.fastq.gz                     1> /dev/null                     2> test_minigut_sample2.bowtie2.log
  echo "Bowtie2 reference: GCA_002596845.1_ASM259684v1_genomic.fna.gz" >test_minigut_sample2_remove_phix.log
  gunzip -c test_minigut_sample2_trimmed_R1.fastq.gz | echo "Read pairs before removal: $((`wc -l`/4))" >>test_minigut_sample2_remove_phix.log
  gunzip -c test_minigut_sample2_phix_unmapped_1.fastq.gz | echo "Read pairs after removal: $((`wc -l`/4))" >>test_minigut_sample2_remove_phix.log

Command exit status:
  -

Command output:
  (empty)

Work dir:
  /Users/rsompallae/biotools/work/d4/0b249504460f911e0ba7e5db73f495

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

could you let me know where can I find the config file to edit and make changes to meet our cluster requirements

**Comment by d4straub** [comment]
Okay, I gave you all information already in the post before, but I'll try to explain. Please read this carefully.
- When you run `nextflow run nf-core/mag -r 1.1.0 -profile test -with-singularity nfcore-mag-1.1.0.img`, the cluster scheduler will not be used and the pipeline will be executed on your login node. 
- This could be the reason why only 1 core is available to you `(Process requirement exceed available CPUs -- req: 2; avail: 1)`. 
- You are not supposed to edit the pipeline files itself, because than you would not run the specified release. To revert what you have done now, use `nextflow pull nf-core/mag -r 1.1.0`.

**About a new config:**
- either add [here](https://github.com/nf-core/configs/tree/master/conf) a profile ([here is how-to](https://github.com/nf-core/configs#adding-a-new-pipeline-specific-config)) that you can then use with `-profile <profile name>` or 
- add `-c <file>` where you specify the [executor](https://www.nextflow.io/docs/latest/executor.html#sge), e.g. the <file> contains: (untested!!):
```
process {
  executor = 'sge'
}
params {
  max_memory = 1000.GB
  max_cpus = 28
  max_time = 168.h
}
```
If you have queues to add, use e.g. ` queue = { task.memory >= 128.GB ? 'smp': task.time <= 20.m ? 'tiny' : task.time > 48.h ? 'long' : 'short'}` in `process`. Please also consult [existing config](https://github.com/nf-core/configs/tree/master/conf) as templates.

**Comment by ramakrishnas** [comment]
Thank you Daniel, I truly appreciate your help. 

It seems to be working now but I'm getting other error, about the data file

-[nf-core/mag] Pipeline completed with errors-
Error executing process > 'busco_db_preparation (bacteria_odb10.2020-03-06.tar)'

Caused by:
  Process `busco_db_preparation (bacteria_odb10.2020-03-06.tar)` terminated with an error exit status (2)

Command executed:

  mkdir buscodb
  tar -xf bacteria_odb10.2020-03-06.tar.gz -C buscodb

Command exit status:
  2

Command output:
  (empty)

Command error:
  
  gzip: stdin: unexpected end of file
  tar: Unexpected EOF in archive
  tar: Unexpected EOF in archive
  tar: Error is not recoverable: exiting now

Work dir:
  /Users/rsompallae/work/6a/0f8c088d9da7fe77f56b6225ef228e

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

**Comment by d4straub** [comment]
This looks like a faulty file download. You could download the database manually and provide it to the pipeline:
`wget "https://busco-data.ezlab.org/v4/data/lineages/bacteria_odb10.2020-03-06.tar.gz"`
and then add to your pipeline command `--busco_reference <path/to/bacteria_odb10.2020-03-06.tar.gz> -resume`
Hope that helps (again). If this does help, it seems to me you may not rely on any automatic file download since these seems to fail on your system frequently.

**Comment by ramakrishnas** [comment]
Thank you so much, finally have it working.

**Comment by d4straub** [comment]
Glad to hear!
I close this issue, feel free to open another one if you have issues with the pipeline.
