### ISSUE TITLE
Renaming of FASTQ (un-gzipped) input files fails

### ISSUE THREAD

**Issue by hoelzer** [nf-core/mag#160]
Hi team!

I experienced a problem w/ the pipeline when using FASTQ files as input (and not `.fastq.gz`) files, see:

https://github.com/nf-core/mag/blob/master/main.nf#L480

The problem is, that regardless of what the input file type is it will be linked to 

```
ln -s "${reads[0]}" "${name}_R1.fastq.gz"
```

So basically, the pipeline does not work atm w/ FASTQ input and should check if a file is gzipped and then handle it appropriately. 

Btw: why anyway perform this `rename_short_read_fastqs` step? For the final documentation?

**Comment by skrakau** [comment]
Hi @hoelzer,

Thanks for reporting this, we will look into this asap. The files are renamed to allow files from different subdirectories with the same basename (otherwise this will cause problems, for example, when processed with FastQC).

**Comment by d4straub** [comment]
Well, its either a bug or a documentation oversight. `.fastq` instead of `.fastq.gz` is suggested in [mag_workflow.png](https://github.com/nf-core/mag/blob/master/docs/images/mag_workflow.png) and also [docs](https://nf-co.re/mag/usage#direct-fastq-input-short-reads-only) specifically say that `.fasta` would work but all examples are with `.fastq.gz`. 

I'd rather classify this as documentation issue & additional feature to support fastq.

**Comment by hoelzer** [comment]
@skrakau thanks! Ah yes, that's a valid point. 

@d4straub yes, the documentation states that `fastq` works but not with the current code. However, it should be rather simple to also support FASTQ as direct input as well.

**Comment by skrakau** [comment]
For now, I updated the docs, but did not add the handling of uncompressed FastQ files, since it would currently require an extra compression process and unnecessary space. See https://github.com/nf-core/mag/pull/195.
