### ISSUE TITLE
Test is erroring out for me

### ISSUE THREAD

**Issue by gailrosen** [nf-core/mag#182]
<!--
# nf-core/mag bug report

Ran this:  nextflow run nf-core/mag -profile test,singularity

Here are the bugs i got:
[execution_trace.txt](https://github.com/nf-core/mag/files/6369736/execution_trace.txt)
[pipeline_report.txt](https://github.com/nf-core/mag/files/6369737/pipeline_report.txt)

**Comment by d4straub** [comment]
Hi there, 

could you give details? Without further information there is no way anybody can help you. I'd like to remind you about the bug report template:

## Check Documentation

I have checked the following places for your error:

- [ ] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [ ] [nf-core/mag pipeline documentation](https://nf-co.re/nf-core/mag/usage)

## Description of the bug



## Steps to reproduce

Steps to reproduce the behaviour:

1. Command line: 
2. See error: 

## Expected behaviour



## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the pipeline
- [ ] The `.nextflow.log` file 

## System

- Hardware: 
- Executor: 
- OS: 
- Version 

## Nextflow Installation

- Version: 

## Container engine

- Engine: 
- version: 
- Image tag: 

## Additional context

**Comment by gailrosen** [comment]
This is so bizarre... I put files and a description before.. I don't know why it didn't post.  I'll put again.  

I was running the following command: "nextflow run nf-core/mag -profile test,singularity"

I got the following reports as bugs.
[pipeline_report.txt](https://github.com/nf-core/mag/files/6371026/pipeline_report.txt)
[execution_trace.txt](https://github.com/nf-core/mag/files/6371027/execution_trace.txt)

**Comment by gailrosen** [comment]
________________________________________

**Comment by d4straub** [comment]
The conversion of the software container failed. Unfortunately singularity conversion seems to fail quite often on some systems when done within Nextflow.

You can solve this by:
- enter the directory where you want to run the pipeline, create directories `./work/singularity/` if they do not exist.
- download the software container manually and move it where the pipeline expects it:
```
singularity pull --name nfcore-magbusco-1.2.0.img docker://nfcore/magbusco:1.2.0
mv nfcore-magbusco-1.2.0.img ./work/singularity/
```

Than start the pipeline as usual.

**Comment by gailrosen** [comment]
I just got "Error executing process > 'remove_phix (test_minigut)'

Caused by:
  Process requirement exceed available CPUs -- req: 2; avail: 1 "

I can easily resolve this -- but if you can let people know the minimum number of CPU threads required to run this, it will help - thanks.

**Comment by d4straub** [comment]
This is a pipeline for high throughput analysis and high performance clusters. If you are eager to investigate how much cores each process requires by default than feel free to check [here](https://github.com/nf-core/mag/blob/master/conf/base.config).

Having said this, of course the pipeline can be restricted to any resources available. So if you would care to read the documentation you would be able to find this out, e.g. [here](https://nf-co.re/usage/configuration?q=max_cpus#max-resources).

**Comment by gailrosen** [comment]
This is helpful!  Thank you!
