### ISSUE TITLE
unable to execute the process NFCORE_MAG:MAG:KRONA_DB

### ISSUE THREAD

**Issue by mathavanpu** [nf-core/mag#369]
hi there,
I am executing the mag pipeline with the following command
 nextflow run nf-core/mag -r 2.2.1 -name metagenome -bg -profile docker -work-dir mag_nfcore/work -params-file nf-params.json
 I got an error message mentioned below. Can you please help me to solve this

nf-core/mag execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 1.
The full error message was:

Error executing process > 'NFCORE_MAG:MAG:KRONA_DB'
Caused by:
  Process `NFCORE_MAG:MAG:KRONA_DB` terminated with an error exit status (1)

Command executed:

  ktUpdateTaxonomy.sh taxonomy
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_MAG:MAG:KRONA_DB":
      ktImportTaxonomy: $(ktImportTaxonomy 2>&1 | sed -n '/KronaTools /p' | sed 's/^.*KronaTools //; s/ - ktImportTaxonomy.*//')
  END_VERSIONS

Command exit status:
  1

Command output:
  
  Creating taxonomy...
  
  Fetching taxdump.tar.gz...
     Fetching checksum...
  Checksum for taxdump.tar.gz does not match server. Retrying...
  Fetching taxdump.tar.gz...
     Fetching checksum...
  
  Update failed.
     Checksum for taxdump.tar.gz still does not match server after retry.

Command error:
  /usr/local/bin/ktUpdateTaxonomy.sh: line 163: [: ==: unary operator expected

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

**Comment by gregorysprenger** [comment]
I've ran into this issue recently as well. I reran the workflow using the `-resume` flag and it worked.

This could be an issue with your internet connection or the server where `taxdump.tar.gz` is being pulled from. The checksum is a unique set of letters and numbers for a specific file (in this case, taxdump.tar.gz). So if the checksum is changed in any way on the file (due to partial download), the precomputed checksum from the server will not equal the checksum that is computed on taxdump.tar.gz after it is downloaded, which will cause this module to terminate.

**Comment by d4straub** [comment]
Thanks gregorysprenger, that sounds correct. The download failed and appending `-resume` should re-download and hopefully succeed. I close the issue but feel free to open another one in case you encounter another problem.
