### ISSUE TITLE
Repeating gtdbtk db download and installation in each resumed run

### ISSUE THREAD

**Issue by eray-sahin** [nf-core/mag#376]
### Description of the bug

Hello,

It is my first time using your great pipeline, and having some failures. Whenever I re-start the pipeline with '-resume', the "gtsdtk" db download and installation is initiated from scratch even there are pre-downloaded tar.gz file and successfully installed database folders. I think that step and temporary folders are not saved in nextflow record. Could you please help me how to skip that step because it takes hours because of download step?

Thank you,

Best regards

**Comment by d4straub** [comment]
Hi there, sorry to hear you are having trouble.
It always helps to get information about what you did, e.g. the command you used to run the pipeline and all other info. Otherwise any attempt to troubleshoot your problem is a shot in the dark. The more info you provide, the more helpful will be answers.

So with the limited info given I'll attempt to answer 
> Could you please help me how to skip that step because it takes hours because of download step?

[`--gtdb false`](https://nf-co.re/mag/2.2.1/parameters#gtdb) might do the trick.

**Comment by d4straub** [comment]
Add to your command:
`--gtdb path/to/gtdbtk_r202_data.tar.gz`, which can be local. That should avoid the download.
see https://nf-co.re/mag/2.2.1/parameters#gtdb
Sorry for the late reply, I somehow missed your most recent comment.

**Comment by skrakau** [comment]
I will close the issue due to inactivity. If the problem still occurs, feel free to open a new issue.
