### ISSUE TITLE
Contributing CoPTR

### ISSUE THREAD

**Issue by ramirobarrantes** [nf-core/mag#701]
Hello, we would like to add CoPTR to the MAG pipeline: 

This is the tutorial on how to run it: https://coptr.readthedocs.io/en/latest/tutorial.html
And this is the paper about it: https://pmc.ncbi.nlm.nih.gov/articles/PMC8896461/

Would it be ok if I add this?

Incidentally, I will be at the Nextflow Summit in Barcelona next week so I was thinking of working on this then.

**Comment by jfy133** [comment]
Hi @ramirobarrantes !

Yes let's talk beforehand to make sure it's in scope! 

I would suggest posting on slack mag channel if you've not already so we can get wider opinions

Otherwise we've got dev hours tomorrow in the nf-core gather.town at 14:00 cest 

And of course it that doesn't work we have the summit :)

**Comment by ramirobarrantes** [comment]
Thank you, just posted this on slack.

**Comment by jfy133** [comment]
Discussion on slack: https://nfcore.slack.com/archives/CE9MS66BS/p1729697976213149

**Comment by jfy133** [comment]
The general conclusion is that there is interest in this, but rather than in a (possible) downstream pipeline as it's a bit too out of scope/specific for mag itself.

The modules/subworkflow will still be created during the hackathon :)
